In [64]:
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import euclidean_distances
from scipy.optimize import linear_sum_assignment
from sklearn.metrics import confusion_matrix

In [65]:
def myKmeans(data, C, K, num_iters=10):
    n, m = data.shape
    for i in range(0, num_iters):
        D = euclidean_distances(data, C)
        Cls = np.argmin(D, axis = 1)
        for k in range(0, K):
            indClass = np.where(Cis == k)
            # DataFromThisClass = np.array(data[indClass,:]) # use a.squeeze(0) if dimension is > 2d
            DataFromThisClass = np.array(data[indClass,:]).squeeze(0)
            C[k,:] = DataFromThisClass.mean(axis=0)
        D = euclidean_distances(data, C)
        Cls = np.argmin(D, axis=1)
        Obj = np.min(D, axis=1).sum()
    return Obj, Cls

In [66]:
def mainFunction(data, K, num_iter):
    n, m = data.shape
    O = np.zeros(num_iter)
    C_all = np.zeros((num_iter, n))
    for i in range(0, num_iter):
        p = np.random.permutation(n) # random ordering of 0 to n-1
        C = data[p[0:K],:] # picking up k random points from data as centers
        Obj, cls = myKmeans(data, C, K)
        O[i] = Obj
        C_all[i,:] = cls.transpose()

    indlowest = np.argmin(O)
    finalClass = C_all[indlowest,:].transpose()
    return K, finalClass

In [67]:
data = np.genfromtxt("../data/mnist_train.csv", delimiter=",", dtype=float)

In [72]:
LabelTrain = data[:,0]
n, m = data.shape
data = data[:, 1:n]
# num_iter = 10 # number of timnes to randomly initialize centers
K = 10 # Number of classes
N = n
Cls = mainFunction(data, K, N)

In [69]:
confMat = np.zeros((K, K))
for k in range(0, K):
    indclass = np.where(LabelTrain == k)
    p, bins = np.histogram(Cls[indclass], bins = [0,1,2,3,4,5,6,7,8,9,10])
    # p += np.histogram(data, bins = [0,1,2,3,4,5,6,7,8,9,10])[0]
    # confMat[k,:] = p.astype('uint8')

TypeError: tuple indices must be integers or slices, not tuple

In [39]:
print(confMat)

[[101. 117. 153. 123.  53. 105.  66. 120.  80.  82.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


In [40]:
confMat = -confMat
row_ind, col_ind = linear_sum_assignment(confMat)
print(row_ind, col_ind)

[0 1 2 3 4 5 6 7 8 9] [2 0 1 3 4 5 6 7 8 9]


In [47]:
misclass = -1*(confMat.sum() - confMat[row_ind, col_ind].sum())
err = misclass / N
print(f"Total percentage of misclassified point: {err}")

Total percentage of misclassified point: -0.847
